Maytitle: WolverineRobotics.github.io
description: >- # this means to ignore newlines until "baseurl:"
  Website for WolverineRobotics
baseurl: "" # the subpath of your site, e.g. /blog
url: "https:/wolverinerobotics.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  WolverineRobotics

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
include: 
  - _pages
collections: 
  pages: 
    output: true 
    permalink: /:name/
header_pages:
  - _pages/home.md
  - _pages/about.md
  - _pages/events.md
  - _pages/sponsors.md
  - _pages/blog.md
  - _pages/contact.md

