title: WolverineRobotics.github.io
description: >-
  Website for WolverineRobotics
baseurl: ""
url: "https://wolverinerobotics.github.io"
github_username: WolverineRobotics

theme: minima
plugins:
  - jekyll-feed
include:
  - _pages
collections:
  pages:
    output: true
    permalink: /:name/
  blogs:
    output: true
    permalink: /blog/:title/
defaults:
  - scope:
      path: ""
      type: blogs
    values:
      layout: post
header_pages:
  - _pages/home.html
  - _pages/about.html
  - _pages/events.html
  - _pages/sponsors.html
  - _pages/blog.html
  - _pages/contact.html
