title: WolverineRobotics.github.io
description: >-
  Website for WolverineRobotics
baseurl: ""
url: "https://wolverinerobotics.github.io"
github_username:  WolverineRobotics

plugins:
  - jekyll-feed
  - jekyll-paginate

theme: minima

include:
  - _pages

header_pages:
  - _pages/home.md
  - _pages/about.md
  - _pages/events.md
  - _pages/sponsors.md
  - _pages/blog.md
  - _pages/contact.md

