title: WolverineRobotics.github.io
description: >- # this means to ignore newlines until "baseurl:"
  Website for WolverineRobotics
baseurl: "" # the subpath of your site, e.g. /blog
url: "https:/wolverinerobotics.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  WolverineRobotics

# Build settings
theme: minima
plugins:
  - jekyll-feed


